### ISSUE TITLE
If I send a interest to get data,how to send data back?

### ISSUE THREAD

**Issue by Heath68** [gujianxiao/ndn-lite-application-for-nRF52840-BLE_version#1]
I read the code and didn`t find the definition of data package.So if I need to send data back,how should I do?

**Comment by peurpdapeurp** [comment]
You should use the interest callback API's from the ndn-lite library.

The general idea of it is to register a prefix with the forwarder, and register a callback function for that prefix so that when you get an interest you can react in the proper way.

The application design logic should be something like this:

1) Register a prefix and interest callback with the forwarder

2) Get an interest -> callback gets triggered -> inside of the on interest callback, send data to the forwarder with the same name -> forwarder will send the data through the interface from which the interest was received, if the name prefixes match

You can look at the forwarder API's here: https://github.com/named-data-iot/ndn-lite/blob/master/forwarder/forwarder.h

**Comment by Heath68** [comment]
"send data to the forwarder with the same name",how to implement it?Use function ndn_forwarder_put_data(uint8_t* data, size_t length)?

**Comment by peurpdapeurp** [comment]
Yes, inside of your on interest callback, you should:

1) Use the encoding API to create a data packet (which you can find here: https://github.com/named-data-iot/ndn-lite/blob/master/encode/encoder.h)
     - make sure that the data packet's name has the original interest's name as a prefix, i.e. if the interest's name was /a/b then the data's name could be /a/b or /a/b/c, etc
2) Use the ndn_forwarder_put_data with a pointer to the buffer that contains your encoded data, as well as the length of your encoded data

**Comment by Heath68** [comment]
I still didn`t get it,how to create a data packet with encoding API?Can you give me a specific example?

**Comment by Heath68** [comment]
Is it right to send a data in on interest callback with following code?
`      ndn_data_t temp_data;
      ndn_data_init(&temp_data);

#ifdef BOARD_1
      char name_string[] = "/NDN-IoT/Board1/TEMP/NOW";
#endif
#ifdef BOARD_2
      char name_string[] = "/NDN-IoT/Board1/TEMP/NOW";
#endif
      ndn_name_from_string(&temp_data.name, name_string, sizeof(name_string));
      uint8_t temp_data_block[256] = {0,1,2};
      ndn_encoder_t encoder;
      encoder_init(&encoder, temp_data_block, 256);
      ndn_data_tlv_encode_digest_sign(&encoder, &temp_data);
      ndn_forwarder_put_data(m_temp_data->encoder, sizeof(encoder));`

**Comment by peurpdapeurp** [comment]
It's very close; for your call to ndn_forwarder_put_data, you should do it like this:

ndn_forwarder_put_data(encoder.output_value, encoder.offset)

The general idea is that the encoder is just a buffer in which the bytes of your data are stored. The offset member of the encoder object tells you the size of the data packet, because that is the size of what was encoded (which was done by the call to ndn_data_tlv_encode_digest_sign).

**Comment by Heath68** [comment]
I‘ve tested the modified code，and didn't work well,I debugged code and find there is something wrong with ndn_data_tlv_encode_digest_sign(&encoder, &temp_data);
I tested like following:
      int ret_val=ndn_data_tlv_encode_digest_sign(&encoder, &temp_data);
      if(ret_val==NDN_SUCCESS){
          blink_led(4);
         }
and LED4 didn't blink.I dont' know whether it is because something wrong with encoder_init() or ndn_data_tlv_encode_digest_sign().

**Comment by peurpdapeurp** [comment]
I see; you should check what the actual value of the return value is, so you can check what the problem might be in ndn-error-code.h

**Comment by Heath68** [comment]
It is because NDN_OVERSIZE,so I should define temp_data_block[256] smaller?

**Comment by peurpdapeurp** [comment]
You should probably define the temp_data_block to be larger if you are getting an NDN_OVERSIZE error. Maybe try making it temp_data_block[500] to see if you still get an error.

**Comment by peurpdapeurp** [comment]
Ah, looking at your code more closely I think you misunderstand what the temp_data_block actually is. That is not where the content of your data is; that is the temporary buffer where the encoding actually occurs. The encoder.output_value is actually just a pointer to the temp_data_block buffer. If you want to set the data of the content, you can do so with a call to ndn_data_set_content, as shown here: https://github.com/named-data-iot/ndn-lite/blob/master/encode/data.h

**Comment by Heath68** [comment]
Still  NDN_OVERSIZE when I set temp_data_block[500] or even [1000]

**Comment by Heath68** [comment]
So if I want to send a data back,I need to:
1. set data content(ndn_data_set_content();)
2.encode the data(ndn_data_tlv_encode_digest_sign();)
3. put encoded data to forwarder(ndn_forwarder_put_data();)
Am I right?

**Comment by Heath68** [comment]
I've changed my code,and it seems work well,I put it here,if there is any mistake,please remind me,it will help me a lot，thanks！
```
    if (schema_trust_flag) {
    //1.send data packet here
    //2.define a data packet
    //3.put content into the data
    //4.encode the data packet with the same prefix with interest
    //5.send data packet to forward
      ndn_data_t temp_data;
      uint8_t temp_content_value[8]={0,1};
#ifdef BOARD_1
      char name_string[] = "/NDN-IoT/Board1/TEMP/NOW";
#endif
#ifdef BOARD_2
      char name_string[] = "/NDN-IoT/Board2/TEMP/NOW";
#endif
      ndn_data_set_content(&temp_data,temp_content_value, sizeof(temp_content_value));
      ndn_name_from_string(&temp_data.name, name_string, sizeof(name_string));

      uint8_t temp_data_block[100] = {0};
      ndn_encoder_t encoder;
      encoder_init(&encoder, temp_data_block, 100);
      ndn_data_tlv_encode_digest_sign(&encoder, &temp_data);
      int  ret_val=ndn_forwarder_put_data(encoder.output_value, encoder.offset);
//        if(ret_val==NDN_SUCCESS){
//          blink_led(4);
//          }
    } 
  }
}
```

**Comment by peurpdapeurp** [comment]
I think your code looks good, so if you don't have any issues then everything should be fine.
