### ISSUE TITLE
How to send an interest to board and get data from board?

### ISSUE THREAD

**Issue by Heath68** [gujianxiao/ndn-lite-application-for-nRF52840-BLE_version#2]
In last issue I finished sending data packet back to forwarder,and I still need to finish the function of Android sending interest and get data from forwarder  but don't know how to use ndn-lite library to implement it,could you please provide some help?

**Comment by peurpdapeurp** [comment]
You can use the API of the ndn-lite Android support library to send an interest to the board; you can find the specific API for that here: https://github.com/gujianxiao/NDN-IoT-Android/blob/master/ndn_lite_support_library/src/main/java/NDNLiteSupport/BLEFace/BLEFace.java
