### ISSUE TITLE
How to register a prefix to listen an interest from Android? 

### ISSUE THREAD

**Issue by Heath68** [gujianxiao/ndn-lite-application-for-nRF52840-BLE_version#3]
Hello,
In the BLE example you've provided the method of registering a prefix to listen to the interest from other board,and I want to know how to register a prefix to listen to the interest from Android,is it the same as board to board communication?If not,could you please provide me with the basic logic?Thanks a lot.

**Comment by peurpdapeurp** [comment]
You do not have to register separate prefixes for Android vs other boards. That is one of the good things about Named Data Networking; everything is abstracted to names, so as long as your board gets an interest that matches the prefix you registered, it does not matter whether it came from the Android phone or another board, it will be processed exactly the same.

If you are wondering how to send an interest from the Android to the board, I would point you to this API: https://github.com/gujianxiao/NDN-IoT-Android/blob/4a3f0df75ddb9f5a21bde8542d45e72f965b03df/ndn_lite_support_library/src/main/java/NDNLiteSupport/BLEFace/BLEFace.java

**Comment by peurpdapeurp** [comment]
You may also find this alternate Android example helpful: https://github.com/peurpdapeurp/ndn-lite-android-support-library/blob/master/android_library_and_example/app/src/main/java/com/example/edwar/ndniotcontroller/MainActivity.java

(I will actually likely be making the NDN IoT example far more similar to that example, as I think it is less confusing than the current one.)

I think I should caution you though, the ndn-lite-support-library and example in that repository aren't up to date, so you might not be able to just copy and paste it. You should just instead look at the code for how to use the ndn-lite-android-support library API's.
