### ISSUE TITLE
Is this line of code useless ?

### ISSUE THREAD

**Issue by paulyu12** [gujianxiao/ndn-lite-application-for-nRF52840-BLE_version#4]
https://github.com/gujianxiao/ndn-lite-application-for-nRF52840-BLE_version/blob/59592dd618834c5d773e8ab8029085160985200e/Application/main.c#L402

In function ndn_forwarder_express_interest(#Line 394), the forwarder forwards Interest to faces according to FIB-nexthops. And we have added FIB-route of /NDN-IoT prefix through ble face.

In short, ndn_forwarder_express_interest(#Line 394) has done what ndn_face_send wants to do(#Line 402). Is that right ?

**Comment by peurpdapeurp** [comment]
Thank you for pointing this out; this made me realize that I have not pushed my changes to this repository for a while; I will try to update it ASAP.

**Comment by peurpdapeurp** [comment]
Just thought I would close this issue, since I am going to be overhauling the BLE example as soon as this issue (https://redmine.named-data.net/issues/4925) gets resolved.
